### ISSUE TITLE
ManagementAccessDecisionVoter bean not created by default

### ISSUE THREAD

**Issue by dragos-patru** [SDA-SE/sda-spring-boot-commons#178]
Hello,

The ManagementAccessDecisionVoter bean is not created with the default server.port & management.server.port configuration.
The workaround is to inject the ports via env vars SERVER_PORT=8080, MANAGEMENT_SERVER_PORT=8081 or set them again in the properties file of an application using the commons lib.

Error: org.sdase.commons.spring.boot.web.auth.SdaAccessDecisionManager required a bean of type 'org.sdase.commons.spring.boot.web.auth.management.ManagementAccessDecisionVoter'

Tested with version: 0.23.0

Kind Regards,
Dragos

**Comment by JoergSiebahn** [comment]
Hi,

thanks for bringing this to our attention. Although, the [server port](https://github.com/SDA-SE/sda-spring-boot-commons/blob/master/sda-commons-web-autoconfigure/src/main/resources/org/sdase/commons/spring/boot/web/defaults.properties#L2) and the [management port](https://github.com/SDA-SE/sda-spring-boot-commons/blob/master/sda-commons-web-autoconfigure/src/main/resources/org/sdase/commons/spring/boot/web/monitoring/monitoring.properties#L2) are configured in the defaults, I can reproduce the error when they are not defined in a service specific `application.properties`. Other properties in that default configuration files affect the service without the need to repeat them. Our internal standard service template contains such an `application.properties` in `src/main/resources` with this content:

```
# App config
spring.application.name=spring-boot-example
server.port=8080
management.server.port=8081
```

@SDA-SE/bedrock we should investigate on this. In the long term I would prefer to have an `application.properties` that does not need to repeat the default values. It seems like properties from the default configuration of the library are not considered early enough. I can see in debugging, that `@ConditionalOnManagementPort` is checked for implementations of [`ManagementAccessDecisionVoter`](https://github.com/SDA-SE/sda-spring-boot-commons/blob/master/sda-commons-web-autoconfigure/src/main/java/org/sdase/commons/spring/boot/web/auth/management/ManagementAccessDecisionVoter.java) 5 times. I would expect a multiple of 3 though. The first three attempts identify a management port of `null` while the later ones evaluate to the configured default `8081`. That leaves the question, why Spring Boot does not provide an `IgnoreSamePortManagementAccessDecisionVoter` in this case. Although that would lead to wrong behavior, it would match the condition in the beginning.

@dragos-patru for now, I suggest to declare the ports again in the `application.properties`.

**Comment by christopher-cudennec** [comment]
Solved by https://github.com/SDA-SE/sda-spring-boot-commons/pull/556
Waiting for release 3.4.7
