### ISSUE TITLE
Request interceptors error: No thread-bound request found 

### ISSUE THREAD

**Issue by dragos-patru** [SDA-SE/sda-spring-boot-commons#203]
Hello,
I'm currently facing one issue which seems to be related to the RequestInterceptors used for tracing and logging of HTTP Requests.
Example:
[        RequestContextHolder.currentRequestAttributes()](https://github.com/SDA-SE/sda-spring-boot-commons/blob/3ab385c398340db74b0ad3394215ad4a29d1690c/sda-commons-web-autoconfigure/src/main/java/org/sdase/commons/spring/boot/web/tracing/TraceTokenClientInterceptor.java#L28)

Context: i'm using a thread pool to fetch & execute some tasks which call other REST services to manipulate data 

The error I have is the one fired from Spring RequestContextHolder.currentRequestAttributes() because the thread which execute the tasks does not have any request atttributes

![image](https://user-images.githubusercontent.com/89182369/222195589-d3e35649-e139-411f-8036-0d929aab2bb2.png)

Do you have any idea how this issue can be fixed ?

Kind Regards,
Dragos

**Comment by JoergSiebahn** [comment]
Thanks for raising this issue and the detailed report, @dragos-patru 

It should be fixed when #204 is merged.
